[project]
name = "g1-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mujoco>=3.7.0",
    "pygame>=2.6.1",
    "unitree-sdk2py",
]

[tool.uv.sources]
unitree-sdk2py = { path = "../unitree_sdk2_python", editable = true }
